[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/politica-privacidad"
  to = "/politica-privacidad.html"
  status = 200

[[redirects]]
  from = "/terminos-condiciones"
  to = "/terminos-condiciones.html"
  status = 200